apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: hello-job
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - echo "Going to wait for 100 sec"; i=1; while [ $i -ne 10 ]; do echo "waiting ${i}0 sec"; sleep 10; i=$(($i+1)); done; echo "Finished"; exit 0
