apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-role # enable submitting kube jobs
rules:
  - apiGroups:
      - '' # An empty string designates the core API group - builtin objects.
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

